
import "./app.css";
import Sidebar from "./sidebar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="App">
          {/* Sidebar always visible */}
          <Sidebar />

          {/* Main content with margin to prevent overlap with Sidebar */}
          <main style={{ marginLeft: '240px', padding: '20px' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}